name: Gcopy

on:
  workflow_dispatch:
  push:
    # CHANGE THIS TO REFERENCE THE BRANCH YOU WANT TO PUSH
    branches: [v4.6.1-a-testingBranch]
  release:
    types: [published]
  # DO NOT TOUCH: this updates the authorization 
  # token so that it keeps working in the future.
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  clasp-update-aio:
    runs-on: ubuntu-latest
    steps:
    - name: Call Reusable Action
      uses: texas-mcallen-mission/deploy-google-app-script-action-typescript/@v3.0.1
      with:
        CLASP_TOKEN_VALUE: ${{ secrets.CLASPRC_JSON }}
        CLASP_TOKEN_NAME: 'CLASPRC_JSON'
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        USES_ORG_SECRET: false # optional.
        # ORG_VISIBILITY: all # optional, default all.
        SCRIPT_ID: ${{ secrets.GCOPY_SCRIPT_ID }}
        PARENT_ID: ${{ secrets.GCOPY_PARENT_ID }} # optional.
        # DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }} # optional.
        CONFIG_DATA: ${{ secrets.DEV_CONFIG_OPTIONS }} # optional.